name: Validate PR on develop branch

on:
    pull_request:
      types: [opened, synchronize]
      branches: [ develop ]
      paths:
        - 'force-app/**'
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache SFDX and plugin
        uses: actions/cache@v3
        with:
          path: |
            ~/.sfdx
            ~/.sfdx/plugins
          key: sfdx-cache-${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            sfdx-cache-${{ runner.os }}-node-

      - name: Install SFDX CLI
        if: ${{ !cache.hit }}
        run: npm install -g sfdx-cli

      - name: Install sfdx-git-delta plugin
        if: ${{ !cache.hit }}
        run: sfdx plugins:install sfdx-git-delta